$(function(){
	$('.xwsd-menu').find('li').hover(function(){
			$(this).addClass('current')
			       .siblings()
				   .removeClass();
			$oIndex=$(this).index();
			$('.xwsd-box').children('div')
			         .eq($oIndex)
					 .removeClass()
				     .siblings()
					 .addClass('hide');
		});
	$('.llxx-menu').find('li').hover(function(){
		$(this).addClass('current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.llxx-box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.djhd-menu').find('li').hover(function(){
		$(this).addClass('current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.djhd-box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.szjy-menu').find('li').hover(function(){
		$(this).addClass('current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.szjy-box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.xjdx-menu').find('li').hover(function(){
		$(this).addClass('current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.xjdx-box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.wsdb_menu').find('li').hover(function(){
		$(this).addClass('wsdb_current')
			   .siblings()
			   .removeClass();
		$('wsb_current').find('a').css('color','#fff');
		$oIndex=$(this).index();
		$('.wsdb_box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.wsdx_menu').find('li').hover(function(){
		$(this).addClass('second_current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.wsdx_box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.lzwh_menu').find('li').hover(function(){
		$(this).addClass('second_current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.lzwh_box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.mllg_menu').find('li').hover(function(){
		$(this).addClass('second_current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.mllg_box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.jlyd_menu').find('li').hover(function(){
		$(this).addClass('second_current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.jlyd_box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.video_menu').find('li').hover(function(){
		$(this).addClass('second_current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.video_box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.wenhua_menu').find('li').hover(function(){
		$(this).addClass('second_current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.wenhua_box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	$('.dxwh_menu').find('li').hover(function(){
		$(this).addClass('second_current')
			   .siblings()
			   .removeClass();
		$oIndex=$(this).index();
		$('.dxwh_box').children('div')
			          .eq($oIndex)
					  .removeClass()
				      .siblings()
					  .addClass('hide');
		});
	})